title: Brajesh Kumar's Portfolio
logo: /portfolio/assets/img/profile.jpg
description: "Machine Learning Engineer | AI Enthusiast"
theme: jekyll-theme-minimal
show_downloads: true

# Sidebar configuration
sidebar:
  profile_image: /portfolio/assets/img/headshot_circle.png
  name: Brajesh Kumar
  title: Machine Learning Engineer | AI Enthusiast
  details:
    - ğŸ“§ Email: [brajesh350194@gmail.com](mailto:brajesh350194@gmail.com)
    - ğŸ’¼ LinkedIn: [brajesh-gupta](https://linkedin.com/in/brajesh-gupta)
    - ğŸ™ GitHub: [@LazyCoderForU](https://github.com/LazyCoderForU)
    - ğŸ“± Mobile: +91-7979911811
  links:
    - text: GitHub
      url: https://github.com/LazyCoderForU
    - text: LinkedIn
      url: https://www.linkedin.com/in/your-linkedin
    - text: LeetCode
      url: https://leetcode.com/your-leetcode
    - text: Email
      url: mailto:brajeshguptaa1@gmail.com
